model:
  name: "sac"
env:
  name: evo-walker
training:
  n_epochs: 0
  batch_size: 512
  warmup_steps: 10000
  max_steps: 200_000
  learn_frequency: 1
  eval_frequency: 10000
  eval_episodes: 1
  learning_rate: 0.00003
  buffer_size: 200000
system:
  seed: 68